[ids]
*

[main]
# 物理 Win 键变成真正的左 Alt
leftmeta = leftalt
# 将物理 Alt 键定义为一个继承 Meta(M) 修饰功能的自定义层
leftalt = layer(meta_mac)

# 创建自定义层并继承大写 M (Meta/Super) 的所有行为
[meta_mac:M]
# 当在 meta_mac 层中按下 c 时，拦截原生的 Super+C 并改发 Ctrl+C
c = C-c
v = C-v
x = C-x
a = C-a
z = C-z
