[helpers]

[shell.files]
"README.md" = ""
dotfiles = ""
dotter = ""
"dotter.arm" = ""
"dotter.exe" = ""
ssh_config = { target = "~/.ssh/config", type = "template" }
gitconfig = { target = "~/.gitconfig", type = "template" }
"cargo_config.toml" = { target = "~/.cargo/config.toml", type = "symbolic" }
npmrc = { target = "~/.npmrc", type = "symbolic" }
"config_starship.toml" = { target = "~/.config/starship.toml", type = "symbolic" }
"config_yazi.toml" = { target = "~/.config/yazi/yazi.toml", type = "symbolic" }
"config_yazi_init.lua" = { target = "~/.config/yazi/init.lua", type = "symbolic" }
"config_pip.conf" = { target = "~/.config/pip/pip.conf", type = "symbolic", if = "dotter.linux" }
nvim = "~/.config/nvim"

[shell.variables]
GFW_HOST = ""
GFW_PORT = ""
ALI_HOST = ""
ALI_PORT = ""
TX_HOST = ""
TX_PORT = ""
RASP_HOST = ""
RASP_PORT = ""
NAS_HOST = ""
NAS_PORT = ""
WS_HOST = ""
WS_PORT = ""
GIT_NAME = ""
GIT_EMAIL = ""


[fish]
depends = ["shell"]

[fish.files]
"fish" = { target = "~/.config/fish", type = "symbolic" }


[ghostty]
depends = ["shell"]

[ghostty.files]
"ghostty" = { target = "~/.config/ghostty", type = "symbolic" }


[settings]
default_target_type = "automatic"
