[helpers]

[shell.files]
"README.md" = ""
dotfiles = ""
dotter = ""
"dotter.arm" = ""
"dotter.exe" = ""
ssh_config = { target = "~/.ssh/config", type = "template" }
gitconfig = { target = "~/.gitconfig", type = "template" }
"cargo_config.toml" = { target = "~/.cargo/config.toml", type = "symbolic" }
npmrc = { target = "~/.npmrc", type = "symbolic" }


[shell.variables]
GFW_HOST = ""
GFW_PORT = ""
ALI_HOST = ""
ALI_PORT = ""
TX_HOST = ""
TX_PORT = ""
RASP_HOST = ""
RASP_PORT = ""
NAS_HOST = ""
NAS_PORT = ""
WS_HOST = ""
WS_PORT = ""
GIT_NAME = ""
GIT_EMAIL = ""


[fish]
depends = ["shell"]

[fish.files]
"fish" = { target = "~/.config/fish", type = "symbolic" }


[settings]
default_target_type = "automatic"
